### ISSUE TITLE
Error after full update Kali and GVM

### ISSUE THREAD

**Issue by wmagliano** [catsploit/catsploit#11]
GVM Version 22.9.1

Kernel 6.6.9 amd-64
Distributor ID:	Kali
Description:	Kali GNU/Linux Rolling
Release:	2024.1
Codename:	kali-rolling

Error:

Traceback (most recent call last):
  File "/home/kali/Downloads/catsploit/./cats-helpers/openvas_helper.py", line 232, in <module>
    helper.start(main)
  File "/home/kali/Downloads/catsploit/cats-helpers/helper.py", line 16, in start
    rval = func(in_param)
           ^^^^^^^^^^^^^^
  File "/home/kali/Downloads/catsploit/./cats-helpers/openvas_helper.py", line 40, in main
    return vulnerability_scan(conf, scan_range, scan_port, scan_protocol)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Downloads/catsploit/./cats-helpers/openvas_helper.py", line 85, in vulnerability_scan
    with Gmp(connection=conn, transform=EtreeCheckCommandTransform()) as gmp:
  File "/usr/lib/python3/dist-packages/gvm/protocols/gmp.py", line 116, in __enter__
    self._gmp = self.determine_supported_gmp()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gvm/protocols/gmp.py", line 108, in determine_supported_gmp
    raise GvmError(
**### gvm.errors.GvmError: Remote manager daemon uses an unsupported version of GMP. The GMP version was 22.5**
2024-03-25 07:48:42,741 Exeption during running task
Traceback (most recent call last):
  File "/home/kali/Downloads/catsploit/cats/server/task.py", line 105, in _launch
    rval = self.task(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Downloads/catsploit/cats/server/server.py", line 164, in task
    return self._do_scan(
           ^^^^^^^^^^^^^^
  File "/home/kali/Downloads/catsploit/cats/server/server.py", line 193, in _do_scan
    for progress, result in ap.vulnerability_scan(
  File "/home/kali/Downloads/catsploit/cats/server/attack_platform.py", line 1136, in vulnerability_scan
    for progres, result in launch_helper(self._ovas_helper, params, logger):
  File "/home/kali/Downloads/catsploit/cats/utils/helperutils.py", line 56, in launch_helper
    raise RuntimeError("Error in helper application")
RuntimeError: Error in helper application

**Comment by YgorAlberto** [comment]
Did you fix the error, im at the same situation here

**Comment by wmagliano** [comment]
pip install gvm-tools==24.3.0

I do that and work again.

**Comment by YgorAlberto** [comment]
I updated to the last version, and it still show an error while generating the report
What script are u using for generating reports?

**Comment by wmagliano** [comment]
if you can... make this...
1) sudo apt update
2) sudo apt upgrade
3) sudo gvm-stop
4) pip install python-gvm==24.3.0
5) pip install gvm-tools==24.3.0
6) sudo greenbone-feed-sync
7) sudo gvm-start
8) Can su access to Greenbone?
9) start catsploit server
10) start catsploit
11) scan 127.0.0.1
12) host list
13) host detail [host_id]

**Comment by YgorAlberto** [comment]
"Can su access to Greenbone?"
How that? 
I couldnt run those comands:
start catsploit server
start catsploit
scan 127.0.0.1
host list
host detail [host_id]
Whare i run this?

If that helps, im not running it in containers. Its is installed on Kali.

**Comment by wmagliano** [comment]
ok...
you need gvm (greenbone) to run vulnerability analysis.

Catsploit is not and all-in-one solution... is and  "all-scripts-in-one" solution.
first you need to install nmap, metasploit and greenbone community .

**Comment by YgorAlberto** [comment]
My environment are the following
I have Kali Linux running GVM installed on it, not in container, and everything are updated.

## KALI
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
VERSION_ID="2024.1"
VERSION="2024.1"

## GVM
gvm-check-setup 23.11.0
  Test completeness and readiness of GVM-23.11.0
Step 1: Checking OpenVAS (Scanner)... 
        OK: OpenVAS Scanner is present in version 22.7.9.
        OK: Notus Scanner is present in version 22.6.2.
        OK: Server CA Certificate is present as /var/lib/gvm/CA/servercert.pem.
Checking permissions of /var/lib/openvas/gnupg/*
        OK: _gvm owns all files in /var/lib/openvas/gnupg
        OK: redis-server is present.
        OK: scanner (db_address setting) is configured properly using the redis-server socket: /var/run/redis-openvas/redis-server.sock
        OK: the mqtt_server_uri is defined in /etc/openvas/openvas.conf
        OK: _gvm owns all files in /var/lib/openvas/plugins
        OK: NVT collection in /var/lib/openvas/plugins contains 89001 NVTs.
        OK: The notus directory /var/lib/notus/products contains 456 NVTs.
Checking that the obsolete redis database has been removed
        OK: No old Redis DB
        OK: ospd-openvas service is active.
        OK: ospd-OpenVAS is present in version 22.6.2.
Step 2: Checking GVMD Manager ... 
        OK: GVM Manager (gvmd) is present in version 23.3.0.
Step 3: Checking Certificates ... 
        OK: GVM client certificate is valid and present as /var/lib/gvm/CA/clientcert.pem.
        OK: Your GVM certificate infrastructure passed validation.
Step 4: Checking data ... 
        OK: SCAP data found in /var/lib/gvm/scap-data.
        OK: CERT data found in /var/lib/gvm/cert-data.
Step 5: Checking Postgresql DB and user ... 
        OK: Postgresql version and default port are OK.
 gvmd      | _gvm               | UTF8     | libc            | en_US.UTF-8 | en_US.UTF-8 |            |           | 
18151|pg-gvm|10|2200|f|22.6||
        OK: At least one user exists.
Step 6: Checking Greenbone Security Assistant (GSA) ... 
        OK: Greenbone Security Assistant is present in version 22.9.1~git.
Step 7: Checking if GVM services are up and running ... 
        OK: gvmd service is active.
        OK: gsad service is active.
Step 8: Checking few other requirements...
        OK: nmap is present.
        OK: ssh-keygen found, LSC credential generation for GNU/Linux targets is likely to work.
        OK: nsis found, LSC credential package generation for Microsoft Windows targets is likely to work.
        OK: xsltproc found.
        WARNING: Your password policy is empty.
        SUGGEST: Edit the /etc/gvm/pwpolicy.conf file to set a password policy.
Step 9: Checking greenbone-security-assistant...
        OK: greenbone-security-assistant is installed

It seems like your GVM-23.11.0 installation is OK.

## GVM-TOOLS
Requirement already satisfied: gvm-tools==24.3.0 in /home/suporte/.local/lib/python3.11/site-packages (24.3.0)
Requirement already satisfied: python-gvm>=23.4.2 in /home/suporte/.local/lib/python3.11/site-packages (from gvm-tools==24.3.0) (24.3.0)
Requirement already satisfied: defusedxml>=0.6 in /usr/lib/python3/dist-packages (from python-gvm>=23.4.2->gvm-tools==24.3.0) (0.7.1)
Requirement already satisfied: lxml>=4.5.0 in /usr/lib/python3/dist-packages (from python-gvm>=23.4.2->gvm-tools==24.3.0) (5.1.0)
Requirement already satisfied: paramiko>=2.7.1 in /usr/lib/python3/dist-packages (from python-gvm>=23.4.2->gvm-tools==24.3.0) (2.12.0)
Requirement already satisfied: typing-extensions>=4.9.0 in /usr/lib/python3/dist-packages (from python-gvm>=23.4.2->gvm-tools==24.3.0) (4.10.0)

## THE PROBLEM

I have the scan finished and ready to make the report.
So, for that, I use a script using a command like the following:

sudo -u _gvm gvm-script --gmp-username user --gmp-password "P@ss" socket --socketpath /var/run/gvmd/gvmd.sock /tmp/gen_report.py 15ce5f51-431f-445a-a4d3-b65dd1d0d61f /tmp/report.xml

This command will generate a XML that later I can use openvasreporting to generate the xlsx

**Comment by wmagliano** [comment]
mmhh...
you use this command with catsploit?
sudo -u _gvm gvm-script --gmp-username user --gmp-password "P@ss" socket --socketpath /var/run/gvmd/gvmd.sock /tmp/gen_report.py 15ce5f51-431f-445a-a4d3-b65dd1d0d61f /tmp/report.xml

**Comment by YgorAlberto** [comment]
I run this command using a normal terminal on kali

**Comment by wmagliano** [comment]
so, it's not catsploit problem. 

the problems was about a problem with catsploit after full update and i find the solution with pip install gvm-tools==24.3.0

**Comment by YgorAlberto** [comment]
The problem is that i do not use catsploit, i was taking a look on it, and I didnt understand how it would be usefull for GVM. I had never seen it before lol.
So based on what you just said, your problem was different from mine.
Thank you btw
